--Article
INSERT INTO ARTICLES VALUES (1, 'Working with MyBatis in Spring', 'Baeldung');
INSERT INTO ARTICLES VALUES (3, 'Working from Home', 'Michel');
INSERT INTO ARTICLES VALUES (5, 'Working every day', 'Raoul');

--Country
INSERT INTO COUNTRY VALUES (1,'CAMEROON','CM');
INSERT INTO COUNTRY VALUES (2,'SOUTH AFRICA','ZA');
INSERT INTO COUNTRY VALUES (3,'UNITED STATES OF AMERICA','US');

