package com.rodatek.poc.api;

import com.rodatek.common.restapi.ApiOperation;

//API documentation per method expose --- usaully generated by swagger
public interface UserApi extends ApiOperation<UserResource> {

   
}
